Update bundled installer to work with pip 1.5
Also added a check that we have the minimum required
versions of pip/virtualenv before creating a bundled
installer.

Verified I could create/install a bundled installer
with these changes and pip 1.5.4.

If you have the wrong version installed, you'll get:

ValueError: pip requires at least version 1.5.0, but version 1.4.1 was found.

Fixes #691.